name: Auto Zip Project

on:
  push:
    branches:
      - master           # or your working branch name
    paths-ignore:
      - 'backups/**'   # prevents infinite backup loops

permissions:
  contents: write

jobs:
  zip_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Ensure the backups folder exists
      - name: Prepare backups folder
        run: mkdir -p backups

      # Create the zip file
      - name: Create new ZIP backup
        run: |
          echo "Creating zip..."
          zip -r "backups/HD-Button.zip" . -x "*.git*" "backups/*" || exit 1
          ls -lh backups

      # Commit and push the ZIP file
      - name: Commit and push ZIP file
        run: |
          if [ -f "backups/HD-Button.zip" ]; then
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add backups/HD-Button.zip
            git commit -m "Auto backup on push" || echo "No changes to commit"
            git push
          else
            echo "ERROR: ZIP file not found!"
            exit 1
          fi
