name: Auto Zip Project

on:
  push:
    branches:
      - master          # or your working branch
    paths-ignore:
      - 'backups/**'  # prevent infinite loop when committing backups

# 👇 This line gives permission for the workflow to push commits
permissions:
  contents: write
      

jobs:
  zip_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean old backups
        run: |
          mkdir -p backups
          rm -f backups/*.zip

      - name: Create new ZIP backup
        run: |
          zip -r backups/HD-Button.zip . -x "*.git*" "backups/*"

      - name: Commit and push ZIP file
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add backups/HD-Buton.zip
          git commit -m "Auto backup on push" || echo "No changes to commit"
          git push

